### ISSUE TITLE
KMS: Address family not supported by protocol: /cloudkms.googleapis.com:443 when calling KeyManagementServiceClient.create(keyManagementServiceSettings).listKeyRings(keyRingsRequest)

### ISSUE THREAD

**Issue by apptio-speravali** [googleapis/java-kms#812]
Thanks for stopping by to let us know something could be better!

#### Environment details

1. Specify the API at the beginning of the title. -> KMS
2. OS type and version: -> Kubernetes POD ,"Alpine Linux 3.15.4"
3. Java version: openjdk 11.0.15 2022-04-19
4.  Scala version:  2.13.8

#### Steps to reproduce

  1. Call the following method-> ```
KeyManagementServiceClient.create(keyManagementServiceSettings).listKeyRings(keyRingsRequest)
and the exception is thrown
```

#### Code example

val cred = ""
  val getCredentials = ServiceAccountCredentials.fromStream(new ByteArrayInputStream(cred.getBytes))
  val kmsClient: KeyManagementServiceClient = getKeyManagementServiceClient
  val keyRingsRequest =
    ListKeyRingsRequest.newBuilder
      .setParent(LocationName.of("projid, "us").toString)
      .setFilter(KeyRingName.of("projid", "us", "keyring").toString)
      .build
  val account = kmsClient.listKeyRings(keyRingsRequest)

  print(account.iterateAll.asScala.headOption)

  def getKeyManagementServiceClient = {
    val keyManagementServiceSettings =
      KeyManagementServiceSettings.newBuilder
        .setCredentialsProvider(FixedCredentialsProvider.create(getCredentials))
        .build
    KeyManagementServiceClient.create(keyManagementServiceSettings)

  }
```

#### Stack trace
```
com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
101
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:112)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:112)
99
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
98
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
97
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
96
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
95
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
94
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
93
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
92
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
91
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:761)
90
	at com.google.common.util.concurrent.ForwardingListenableFuture.addListener(ForwardingListenableFuture.java:47)
89
	at com.google.api.core.ApiFutureToListenableFuture.addListener(ApiFutureToListenableFuture.java:51)
88
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1105)
87
	at com.google.api.core.ApiFutures.addCallback(ApiFutures.java:62)
86
	at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:67)
85
	at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:87)
84
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
83
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
82
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
81
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
80
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
79
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
78
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
77
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
76
	at java.base/java.lang.Thread.run(Thread.java:829)
75
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
74
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
73
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
72
		at com.google.cloud.kms.v1.KeyManagementServiceClient.listKeyRings(KeyManagementServiceClient.java:262)
71
		at com.apptio.computeservice.data.bigquery.kms.BigQueryKmsService.getKmsRing(BigQueryKmsService.scala:21)
70
		at com.apptio.computeservice.data.bigquery.kms.BigQueryKmsService.$anonfun$createKmsKeyAndAttachRoleToBigQueryServiceAccount$1(BigQueryKmsService.scala:62)
69
		at com.apptio.computeservice.data.bigquery.ConnectionFactory.executeKmsService(ConnectionFactory.scala:84)
68
		at com.apptio.computeservice.data.bigquery.kms.BigQueryKmsService.createKmsKeyAndAttachRoleToBigQueryServiceAccount(BigQueryKmsService.scala:69)
67
		at com.apptio.computeservice.data.bigquery.BigQueryDataClient.initializeResources(BigQueryDataClient.scala:27)
66
		at com.apptio.computeservice.registerenvironment.RegisterEnvironmentExecutor.register(RegisterCustomerExecutor.scala:14)
65
		at com.apptio.computeservice.server.ComputeService.registerEnvironment(ComputeService.scala:247)
64
		at com.apptio.computeservice.grpc.ComputeServiceGrpc$MethodHandlers.invoke(ComputeServiceGrpc.java:1194)
63
		at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
62
		at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
61
		at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
60
		at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
59
		at io.envoyproxy.pgv.grpc.ValidatingServerInterceptor$1.onHalfClose(ValidatingServerInterceptor.java:41)
58
		at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:352)
57
		at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
56
		at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
55
		at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
54
		... 3 common frames omitted
53
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
52
	at io.grpc.Status.asRuntimeException(Status.java:535)
51
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:542)
50
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
49
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
48
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
47
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:535)
46
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
45
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
44
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
43
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
42
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
41
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
40
	... 3 common frames omitted
39
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: /cloudkms.googleapis.com:443
38
Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol
37
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
36
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
35
	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.connect(Socket.java:312)
34
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
33
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:138)
32
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
31
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
30
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
29
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
28
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
27
	at io.grpc.netty.shaded.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
26
	at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:157)
25
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
24
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
23
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
22
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:457)
21
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:942)
20
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel.connect(AbstractChannel.java:229)
19
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:306)
18
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
17
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
16
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:259)
15
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:66)
14
	at io.grpc.internal.InternalSubchannel$1EndOfCurrentBackoff.run(InternalSubchannel.java:280)
13
	at io.grpc.SynchronizationContext$ManagedRunnable.run(SynchronizationContext.java:182)
12
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
11
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
10
	at io.grpc.SynchronizationContext$1.run(SynchronizationContext.java:155)
9
	at io.grpc.netty.shaded.io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
8
	at io.grpc.netty.shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
7
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
6
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
5
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
4
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
3
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
1
	at java.base/java.lang.Thread.run(Thread.java:829)
```

#### Any additional information below
Note: The issue does not reproduce if the code is run in a stand-alone program when executing in the main method.
The code is deployed in Kubernetes POD and when the application is run and when an internal gRPC API is called whose purpose is to call the GCP KMS SDK to create the KMS keys the above error occurs.

#### MVN 
<dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-kms</artifactId>
            <version>2.5.3</version>
        </dependency>

Thanks!

**Comment by apptio-speravali** [comment]
This is caused due to creating a fat jar using maven . 
Not a issue .

**Comment by BobDu** [comment]
> This is caused due to creating a fat jar using maven . Not a issue .

sorry to disturb you.
I had the same issue.

Can you share you how to fix it in the end?
@apptio-speravali
